AllCops:
  Exclude:
    - 'db/migrate/**/'
    - 'db/schema.rb'
    - 'bin/bundle' 


Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 200

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 50
