# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#

default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
development:
  <<: *default
  database: chat_development
  username: postgres
  password: 123456789
  host: localhost
test:
  database: chat_test
  adapter: postgresql
  encoding: unicode
  pool: 5
 
#   username: postgres
#   password: 123456789

